FROM ruby:2.6.4

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo
ENV APP_ROOT /Contrail

#RSpec用
RUN apt-get update -qq && apt-get install -y chromium-driver

RUN mkdir /noto
ADD https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip /noto
WORKDIR /noto
RUN unzip NotoSansCJKjp-hinted.zip && \
    mkdir -p /usr/share/fonts/noto && \
    cp *.otf /usr/share/fonts/noto && \
    chmod 644 -R /usr/share/fonts/noto/ && \
    #フォントキャッシュの更新
    fc-cache -fv

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev vim --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# yarn install
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update -qq && apt-get install -y yarn --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# node install
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq && apt-get install -y default-mysql-client --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /Contrail
WORKDIR $APP_ROOT

COPY Gemfile /$APP_ROOT
COPY Gemfile.lock /$APP_ROOT

RUN gem install bundler
RUN bundle install

COPY . $APP_ROOT

EXPOSE 3000
